package:
  name: testrepository
  version: "0.0.20"

source:
  fn: testrepository-0.0.20.tar.gz
  url: https://pypi.python.org/packages/source/t/testrepository/testrepository-0.0.20.tar.gz
  md5: f648b0aceeca4fcd5f8a62eeedea289b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  #entry_points:
  #  - testr = testrepository.setuptools_command:Testr

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - fixtures
    - python-subunit >=0.0.18
    - testtools >=0.9.30

  run:
    - python
    - setuptools
    - fixtures
    - python-subunit >=0.0.18
    - testtools >=0.9.30

test:
  # Python imports
  imports:
    - testrepository
    - testrepository.arguments
    - testrepository.commands
    - testrepository.repository
    - testrepository.ui

  commands:
    - testr --help

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://launchpad.net/testrepository
  license: BSD License or Apache Software License
  summary: 'A repository of test results.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
